title = "InnerWorldApp Gitleaks Configuration"

[extend]
path = "https://raw.githubusercontent.com/gitleaks/gitleaks/master/config/gitleaks.toml"

# Custom rules for InnerWorldApp
[[rules]]
id = "openai-api-key"
description = "OpenAI API Key"
regex = '''sk-[A-Za-z0-9]{48}'''

[[rules]]
id = "apple-team-id"
description = "Apple Team ID"
regex = '''[A-Z0-9]{10}'''

[[rules]]
id = "neo4j-password"
description = "Neo4j Password"
regex = '''(?i)(neo4j.*password|password.*neo4j)[\s]*[:=][\s]*["\']?([^"\'\s]+)'''

# Allowlist for example files
[[rules.allowlist]]
description = "Example terraform.tfvars files"
paths = [
    '''.*terraform\.tfvars\.example$''',
    '''.*\.md$''',
    '''.*README.*'''
]