title = "InnerWorldApp Gitleaks Configuration"

# Custom allowlist paths - exclude .env and example files globally
[allowlist]
paths = [
  '''.*\.env$''',
  '''.*\.env\..*$''', 
  '''.*\.example$''',
  '''.*terraform\.tfvars\.example$''',
  '''.*\.md$''',
  '''.*README.*''',
  '''.*\.git/.*'''
]

# Custom rules for InnerWorldApp specific patterns
[[rules]]
id = "openai-api-key"
description = "OpenAI API Key"
regex = '''sk-[A-Za-z0-9]{48}'''

[[rules]]
id = "apple-team-id"
description = "Apple Team ID" 
regex = '''[A-Z0-9]{10}'''

[[rules]]
id = "neo4j-password"
description = "Neo4j Password"
regex = '''(?i)(neo4j.*password|password.*neo4j)[\s]*[:=][\s]*["\']?([^"\'\s]+)'''