# Gitleaks configuration for InnerWorldApp
# Comprehensive secret detection for iOS AR app with API integrations

title = "InnerWorldApp Gitleaks Config"

# Global rules
[extend]
# Use default gitleaks rules as base
useDefault = true

# Custom rules for this project
[[rules]]
id = "openai-api-key"
description = "OpenAI API Key"
regex = '''sk-[a-zA-Z0-9]{48}'''
keywords = ["sk-"]

[[rules]]
id = "openrouter-api-key"
description = "OpenRouter API Key"
regex = '''sk-or-[a-zA-Z0-9-_]{43}'''
keywords = ["sk-or-"]

[[rules]]
id = "neo4j-password"
description = "Neo4j Database Password"
regex = '''neo4j\+s?://[^:]+:([^@]+)@'''
keywords = ["neo4j://", "neo4j+s://"]

[[rules]]
id = "neo4j-uri"
description = "Neo4j Connection URI"
regex = '''neo4j\+s?://[a-zA-Z0-9.-]+:[0-9]+'''
keywords = ["neo4j://", "neo4j+s://"]

[[rules]]
id = "ios-app-store-key"
description = "iOS App Store Connect API Key"
regex = '''-----BEGIN PRIVATE KEY-----[A-Za-z0-9+/\s]+=*-----END PRIVATE KEY-----'''
keywords = ["BEGIN PRIVATE KEY"]

[[rules]]
id = "ios-provisioning-profile"
description = "iOS Provisioning Profile"
regex = '''[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}\.mobileprovision'''
keywords = [".mobileprovision"]

[[rules]]
id = "testflight-key"
description = "TestFlight API Key"
regex = '''[A-Z0-9]{10}'''
keywords = ["testflight", "TestFlight"]

[[rules]]
id = "firebase-config"
description = "Firebase Configuration"
regex = '''AIza[0-9A-Za-z\\-_]{35}'''
keywords = ["AIza"]

[[rules]]
id = "swift-hardcoded-key"
description = "Hardcoded API key in Swift"
regex = '''(apiKey|API_KEY|secretKey|SECRET_KEY)\s*[=:]\s*["'][^"']{20,}["']'''
keywords = ["apiKey", "API_KEY", "secretKey", "SECRET_KEY"]

[[rules]]
id = "crisis-hotline-test-numbers"
description = "Test crisis hotline numbers (should not be hardcoded)"
regex = '''\b(555-0[0-9]{3}|1-555-[0-9]{3}-[0-9]{4})\b'''
keywords = ["555-", "hotline", "crisis"]

# iOS specific file exclusions
[allowlist]
description = "Allowlist for iOS development files"
files = [
    '''.*\.storyboard$''',
    '''.*\.xib$''',
    '''.*\.xcassets/.*''',
    '''.*\.lproj/.*''',
    '''.*Package\.swift$''',
    '''.*\.xcconfig$''',
    '''.*\.entitlements$''',
    '''.*\.plist$''',
    '''.*\.md$''',
    '''.*\.txt$''',
    '''.*\.gitignore$''',
    '''.*\.gitleaks\.toml$''',
    '''.*\.yml$''',
    '''.*\.yaml$'''
]

# Paths to exclude from scanning
paths = [
    '''.*\.git/.*''',
    '''.*build/.*''',
    '''.*DerivedData/.*''',
    '''.*\.xcodeproj/xcuserdata/.*''',
    '''.*\.xcworkspace/xcuserdata/.*''',
    '''.*Pods/.*''',
    '''.*\.build/.*''',
    '''.*fastlane/.*''',
    '''.*node_modules/.*''',
    '''.*\.swiftpm/.*'''
]

# Regex patterns to exclude
regexes = [
    '''DEADBEEF''',  # Common placeholder
    '''12345678''',  # Common placeholder
    '''example\.com''',  # Example domains
    '''localhost''',   # Local development
    '''127\.0\.0\.1''', # Local IP
    '''0\.0\.0\.0''',   # Placeholder IP
    '''INSERT_API_KEY_HERE''', # Placeholder text
    '''YOUR_API_KEY''',        # Placeholder text
    '''TODO:''',               # TODO comments
    '''FIXME:''',              # FIXME comments
    '''XXX:'''                 # XXX comments
]

# Entropy detection settings
[allowlist.entropy]
min = 3.5
max = 7.0
group = 1

# Stop scanning after finding this many secrets
[allowlist.stopwords]
stopwords = [
    "example",
    "test",
    "demo",
    "placeholder",
    "mock",
    "fake",
    "sample"
]
