# Pre-commit hooks configuration for InnerWorldApp
# Comprehensive code quality and security checks for iOS AR app

repos:
  # Gitleaks for secret detection
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        name: Detect secrets with Gitleaks
        description: Scan for hardcoded secrets, API keys, and credentials
        entry: gitleaks detect --source . --config .gitleaks.toml --verbose --no-git
        language: golang
        types: [text]
        pass_filenames: false

  # Basic file quality checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
        description: Remove trailing whitespace from all files
        exclude: '.*\.(storyboard|xib|xcassets)$'
      
      - id: end-of-file-fixer
        name: Fix end of files
        description: Ensure files end with newline
        exclude: '.*\.(storyboard|xib|xcassets|plist)$'
      
      - id: check-yaml
        name: Check YAML syntax
        description: Validate YAML files
        files: \.(yaml|yml)$
      
      - id: check-json
        name: Check JSON syntax
        description: Validate JSON files
        files: \.json$
        exclude: '.*\.xcodeproj/.*\.json$'
      
      - id: check-merge-conflict
        name: Check for merge conflicts
        description: Detect merge conflict markers
      
      - id: check-case-conflict
        name: Check for case conflicts
        description: Detect case-insensitive filename conflicts
      
      - id: check-added-large-files
        name: Check for large files
        description: Prevent large files from being committed
        args: ['--maxkb=10240']  # 10MB limit
        exclude: '.*\.(reality|usdz|ipa|dSYM)$'
      
      - id: detect-private-key
        name: Detect private keys
        description: Scan for private keys and certificates
        exclude: '.*\.md$'

  # Swift/iOS specific checks
  - repo: https://github.com/realm/SwiftLint
    rev: 0.54.0
    hooks:
      - id: swiftlint
        name: SwiftLint
        description: Lint Swift code for style and conventions
        entry: swiftlint lint --strict --config .swiftlint.yml
        language: swift
        files: \.swift$
        types: [file]
        require_serial: false

  # Additional security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: Detect secrets (alternative)
        description: Additional secret detection with different patterns
        args: ['--baseline', '.secrets.baseline']
        exclude: '.*\.(storyboard|xib|xcassets|plist)$'

  # File formatting
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
      - id: black
        name: Format Python files
        description: Auto-format Python scripts
        files: \.py$
        exclude: '^(build/|\.build/)'

  # Documentation checks
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        name: Lint Markdown
        description: Check markdown files for style issues
        args: ['--config', '.markdownlint.json']
        files: \.md$

  # iOS specific validations
  - repo: local
    hooks:
      # Custom hook to validate iOS project structure
      - id: validate-ios-project
        name: Validate iOS project structure
        description: Check for required iOS project files and structure
        entry: scripts/validate-ios-project.sh
        language: script
        pass_filenames: false
        always_run: true
      
      # Custom hook to check for hardcoded strings
      - id: check-hardcoded-strings
        name: Check for hardcoded strings
        description: Scan Swift files for potential hardcoded strings
        entry: scripts/check-hardcoded-strings.sh
        language: script
        files: \.swift$
        types: [file]
      
      # Custom hook to validate API endpoint URLs
      - id: validate-api-endpoints
        name: Validate API endpoints
        description: Check that API endpoints use environment variables
        entry: scripts/validate-api-endpoints.sh
        language: script
        files: \.swift$
        types: [file]
      
      # Custom hook to check crisis resources
      - id: validate-crisis-resources
        name: Validate crisis resources
        description: Ensure crisis resources are externalized and not hardcoded
        entry: scripts/validate-crisis-resources.sh
        language: script
        files: \.swift$
        types: [file]

# Global settings
default_language_version:
  python: python3.12

# Exclude patterns
exclude: |
  (?x)^(
    .*\.xcodeproj/.*|
    .*\.xcworkspace/.*|
    .*\.storyboard$|
    .*\.xib$|
    .*\.xcassets/.*|
    .*\.lproj/.*|
    build/.*|
    DerivedData/.*|
    Pods/.*|
    .*\.generated\.swift$|
    .*\.pb\.swift$
  )$

# Fail fast - stop on first failure
fail_fast: false

# Minimum pre-commit version
minimum_pre_commit_version: '3.6.0'
