name: Test Workflow

on:
  push:
    branches: [ infra/* ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: echo "Workflow syntax is working"
